### ISSUE TITLE
Support for typechecking template names

### ISSUE THREAD

**Issue by danlamanna** [Viicos/django-autotyping#51]
Is it possible to add typechecking to `render` and the other methods which take a `template_name` (https://docs.djangoproject.com/en/5.0/topics/templates/#module-django.template.loader) to ensure they're using existing template files? Or would this be too awkward/infeasible because of the number of possible files?

**Comment by Viicos** [comment]
Thanks for opening this issue.

This was a feature I had in mind, and could expanded with an LSP implementation of the Django template engine.

As a first step, supporting the template file name could be great. Usually for a single `Literal` with multiple strings, it works pretty well:

**Comment by Viicos** [comment]
Did a simple test on a relatively big project (400 templates, we are not making use of templates), and autocomplete is perfectly fine. Only issue though with `pyright` is, the autocomplete gets cut off:

![image](https://github.com/Viicos/django-autotyping/assets/65306057/ac33695a-463f-46f1-bec1-6d670b16bf36)

The ellipsis is added by Pylance, which is pretty inconvenient. This was raised [here](https://github.com/microsoft/pylance-release/issues/5116) but will not be supported. I believe the limit is set in `pyright`, so I might provide a monkeypatch if possible.

**Comment by Viicos** [comment]
This is implemented in version `0.5.0` which was just released.
